
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksfklkxprdjlfsdehcjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZmtsa3hwcmRqbGZzZGVoY2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTIzNjIsImV4cCI6MjA2MzM4ODM2Mn0.BBsm5wlGpMGKOyY7V-8rigxkNzWdUUhWN2vC7DxuWUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
